
#ifndef CONFIG_H
#define CONFIG_H

#define SYSTEM_VERSION_MAJOR 1
#define SYSTEM_VERSION_MINOR 0
#define SYSTEM_VERSION_PATCH 0
#define SYSTEM_BUILD_NUMBER 001

// ==================== HARDWARE CONFIGURATION ====================
s
#define LED_STATUS_PIN 13
#define LED_STROBE_PIN_1 2
#define LED_STROBE_PIN_2 3
#define AUDIO_PWM_PIN 4
#define AUDIO_ENABLE_PIN 5
#define EMERGENCY_SERVO_PIN 6

#define ULTRASONIC_TRIG_1 7 // Front sensor
#define ULTRASONIC_ECHO_1 8
#define ULTRASONIC_TRIG_2 9 // Left sensor
#define ULTRASONIC_ECHO_2 10
#define ULTRASONIC_TRIG_3 11 // Right sensor
#define ULTRASONIC_ECHO_3 12

#define BATTERY_VOLTAGE_PIN A0
#define TEMPERATURE_SENSOR_PIN A1
#define LIGHT_SENSOR_PIN A2
#define HUMIDITY_SENSOR_PIN A3
#define PRESSURE_SENSOR_PIN A4
#define CURRENT_SENSOR_PIN A5
#define WIND_SPEED_PIN A6
#define PRECIPITATION_PIN A7

#define VENTILATION_CONTROL_PIN 14
#define HEATER_CONTROL_PIN 15
#define DESICCANT_CONTROL_PIN 16
#define EMERGENCY_BEACON_PIN 17
#define SYSTEM_ISOLATION_PIN 18
#define TELEMETRY_BOOST_PIN 19

#define RAIL_12V_ENABLE_PIN 20
#define RAIL_5V_ENABLE_PIN 21
#define RAIL_3V3_ENABLE_PIN 22

// ==================== OPERATIONAL PARAMETERS ====================

#define BIRD_DETECTION_RANGE_M 100
#define BIRD_ALERT_DISTANCE_M 50
#define BIRD_EMERGENCY_DISTANCE_M 20
#define BIRD_MINIMUM_SIZE_CM 15
#define BIRD_MAXIMUM_SIZE_CM 200
#define BIRD_SPEED_THRESHOLD_MPS 2.0
#define MAX_TRACKED_BIRDS 10
#define DETECTION_CONFIDENCE_THRESHOLD 70

#define LED_MAX_BRIGHTNESS 255
#define LED_STROBE_FREQUENCY_HZ 10
#define LED_THERMAL_LIMIT_C 70.0
#define LED_MAX_CONTINUOUS_TIME_MS 5000
#define LED_COOLDOWN_TIME_MS 2000
#define REFLECTIVE_TAPE_EFFECTIVENESS 0.9

#define AUDIO_MAX_VOLUME_DB 85
#define AUDIO_SAMPLE_RATE_HZ 8000
#define AUDIO_BUFFER_SIZE 256
#define ULTRASONIC_MIN_FREQ_HZ 17000
#define ULTRASONIC_MAX_FREQ_HZ 24000
#define DISTRESS_CALL_DURATION_MS 2000
#define AUDIO_PATTERN_ROTATION_TIME_MS 30000

#define BATTERY_MIN_VOLTAGE_V 10.5
#define BATTERY_MAX_VOLTAGE_V 16.8
#define BATTERY_LOW_WARNING_V 11.0
#define BATTERY_CRITICAL_V 10.0
#define POWER_EFFICIENCY_TARGET 0.95
#define THERMAL_SHUTDOWN_TEMP_C 75.0
#define MAX_CURRENT_DRAW_A 8.0

#define WEATHER_UPDATE_INTERVAL_MS 5000
#define CRITICAL_TEMPERATURE_HIGH_C 50.0
#define CRITICAL_TEMPERATURE_LOW_C -10.0
#define CRITICAL_HUMIDITY_PERCENT 90.0
#define CRITICAL_WIND_SPEED_MPS 15.0
#define CRITICAL_PRESSURE_DROP_HPA 20.0
#define ENCLOSURE_IP_RATING 65

#define EMERGENCY_RESPONSE_TIME_MS 500
#define EMERGENCY_TIMEOUT_MS 30000
#define HEALTH_CHECK_INTERVAL_MS 5000
#define MAX_EMERGENCY_ACTIVATIONS 3
#define EMERGENCY_BEACON_DURATION_MS 60000
#define AUTO_RECOVERY_ATTEMPTS 3

#define SERIAL_BAUD_RATE 115200
#define WIFI_TIMEOUT_MS 10000
#define TELEMETRY_INTERVAL_MS 5000
#define COMMAND_TIMEOUT_MS 1000
#define HEARTBEAT_INTERVAL_MS 30000

// ==================== SYSTEM LIMITS ====================

#define MAX_SYSTEM_WEIGHT_G 1500
#define MAX_SYSTEM_COST_INR 50000
#define CURRENT_SYSTEM_WEIGHT_G 850
#define CURRENT_SYSTEM_COST_INR 38500

#define DETECTION_ACCURACY_TARGET 0.95
#define FALSE_POSITIVE_RATE_MAX 0.05
#define DETERRENT_SUCCESS_RATE_TARGET 0.90
#define SYSTEM_AVAILABILITY_TARGET 0.99
#define RESPONSE_TIME_TARGET_MS 100

#define OPERATING_TEMP_MIN_C -10
#define OPERATING_TEMP_MAX_C 50
#define OPERATING_HUMIDITY_MAX_PERCENT 95
#define OPERATING_ALTITUDE_MAX_M 3000
#define WIND_RESISTANCE_MAX_MPS 30
#define VIBRATION_RESISTANCE_G 5.0

// ==================== FEATURE F
#define ENABLE_BIRD_DETECTION 1
#define ENABLE_VISUAL_DETERRENT 1
#define ENABLE_AUDIO_DETERRENT 1
#define ENABLE_WEATHER_PROTECTION 1
#define ENABLE_EMERGENCY_SYSTEM 1
#define ENABLE_POWER_MANAGEMENT 1
#define ENABLE_TELEMETRY 1

#define ENABLE_DEBUG_OUTPUT 1
#define ENABLE_SERIAL_COMMANDS 1
#define ENABLE_SELF_TEST 1
#define ENABLE_PERFORMANCE_MONITORING 1
#define ENABLE_DATA_LOGGING 1

#define ENABLE_ADAPTIVE_DETERRENCE 1
#define ENABLE_MACHINE_LEARNING 0
#define ENABLE_PREDICTIVE_ANALYSIS 0
#define ENABLE_SWARM_COORDINATION 0

#define ENABLE_WATCHDOG_TIMER 1
#define ENABLE_FAILSAFE_MODE 1
#define ENABLE_EMERGENCY_OVERRIDE 1
#define ENABLE_THERMAL_PROTECTION 1
#define ENABLE_OVERCURRENT_PROTECTION 1

// ==================== TIMING CONSTANTS ====================

#define MAIN_LOOP_FREQUENCY_HZ 20
#define SENSOR_UPDATE_FREQUENCY_HZ 10
#define CONTROL_UPDATE_FREQUENCY_HZ 50
#define TELEMETRY_UPDATE_FREQUENCY_HZ 1
#define HEALTH_CHECK_FREQUENCY_HZ 0.2
#define SENSOR_READ_TIMEOUT_MS 100
#define COMMAND_EXECUTION_TIMEOUT_MS 5000
#define EMERGENCY_ACTIVATION_TIMEOUT_MS 500
#define SYSTEM_STARTUP_TIMEOUT_MS 10000
#define COMMUNICATION_TIMEOUT_MS 3000

#define STARTUP_DELAY_MS 2000
#define COMPONENT_INIT_DELAY_MS 100
#define SENSOR_STABILIZATION_DELAY_MS 500
#define POWER_RAIL_STARTUP_DELAY_MS 50
#define EMERGENCY_RESPONSE_DELAY_MS 10

#define TEMPERATURE_CALIBRATION_OFFSET 0.0
#define HUMIDITY_CALIBRATION_OFFSET 0.0
#define PRESSURE_CALIBRATION_OFFSET 0.0
#define VOLTAGE_CALIBRATION_MULTIPLIER 1.0
#define CURRENT_CALIBRATION_MULTIPLIER 1.0

#define AUDIO_VOLUME_CALIBRATION 1.0
#define FREQUENCY_CALIBRATION_OFFSET 0.0
#define MICROPHONE_SENSITIVITY 1.0

#define ULTRASONIC_SPEED_OF_SOUND_MPS 343.0
#define ULTRASONIC_TEMPERATURE_COMPENSATION 1
#define DISTANCE_MEASUREMENT_OFFSET_CM 0.0

// ==================== NETWORK CONFIGURATION ====================

#ifdef ENABLE_TELEMETRY

#define WIFI_SSID "DRONE_NETWORK"
#define WIFI_PASSWORD "DroneNet2024"
#define WIFI_CONNECTION_ATTEMPTS 10

#define GROUND_STATION_IP "192.168.1.100"
#define GROUND_STATION_PORT 8080
#define TELEMETRY_PACKET_SIZE 256

#define EMERGENCY_FREQUENCY_MHZ 433.92
#define EMERGENCY_TRANSMISSION_POWER_DBM 20
#endif

#define TELEMETRY_BUFFER_SIZE 512
#define COMMAND_BUFFER_SIZE 128
#define LOG_BUFFER_SIZE 1024
#define AUDIO_BUFFER_SIZE 256
#define SENSOR_HISTORY_SIZE 20

#define MAX_LOG_ENTRIES 100
#define MAX_TELEMETRY_QUEUE 50
#define MAX_COMMAND_QUEUE 10
#define MAX_ERROR_MESSAGES 20

#if CURRENT_SYSTEM_WEIGHT_G > MAX_SYSTEM_WEIGHT_G
#error "System weight exceeds design limit"
#endif

#if CURRENT_SYSTEM_COST_INR > MAX_SYSTEM_COST_INR
#error "System cost exceeds budget limit"
#endif

#define VALIDATE_RANGE(value, min, max) ((value) >= (min) && (value) <= (max))
#define VALIDATE_PIN(pin) ((pin) >= 0 && (pin) <= 23)
#define VALIDATE_PERCENTAGE(value) VALIDATE_RANGE(value, 0, 100)

#define HARDWARE_REVISION "Rev 1.0"
#define PCB_VERSION "PCB-001"
#define ENCLOSURE_MODEL "IP65-DRONE-001"
#define MOUNTING_SYSTEM "UNIVERSAL-DRONE-MOUNT"

#define SOFTWARE_BUILD_DATE __DATE__
#define SOFTWARE_BUILD_TIME __TIME__
#define COMPILER_VERSION __VERSION__

#define CE_MARKING_REQUIRED 1
#define FCC_COMPLIANCE_REQUIRED 1
#define RoHS_COMPLIANT 1
#define AVIATION_SAFETY_COMPLIANT 1

#endif